### ISSUE TITLE
다크모드 (메인페이지) by 팀장 김선효

### ISSUE THREAD

**Issue by kthss01** [sunyos/FundingProject#13]
다크모드 이슈 정리 by 팀원 김태훈
다른 페이지 (파트)에서는 미적용, 메뉴바 css 미적용
-> css 외부링크 각 페이지마다 추가해야함
-> 각 페이지마다 css 구성이 다르기때문에 개별적으로 추가해야한다고함
특정 페이지에서 다크모드 활성화시 다른 페이지에서는 적용 안됨 (다크모드 활성화 유지 안됨)
	-> json, db 등을 활용해서 상태 저장을 하면 좋을것 같음 (건의내역)
* 현재 메인 페이지만 간단히 적용 후 커밋해버린 상황이라고 함

추가 건의사항
	애니메이션 작업이 들어가면 좋을거 같음

**Comment by sunyoring** [comment]
세션에 컬러모드 타입을 저장해 한번 설정했을 경우 모든 페이지에서 같은 모드로 유지되게 업데이트 고려
